spring.application.name=Resenha

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME_SPRING}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD_POSTGRES}

spring.datasource.driver-class-name=org.postgresql.Driver

server.error.include-stacktrace=never