CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                       email VARCHAR(100) NOT NULL UNIQUE,
                       password VARCHAR(255) NOT NULL,
                       role VARCHAR(20) NOT NULL,
                       player_id BIGINT NOT NULL UNIQUE,

                       CONSTRAINT pk_users PRIMARY KEY (id),

                       CONSTRAINT fk_users_player
                           FOREIGN KEY (player_id)
                               REFERENCES players(id)
);